config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :videos do
    resources :comments
  end
  resource :session, :only => [:new, :create, :destroy]
  resources :notifications
  resources :users, :except => [:destroy]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
  end
  resources :messages, only: [:new, :create]

  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  get 'signin' => 'sessions#new', as: 'signin'
  get 'signout' => 'sessions#destroy', as: 'signout'
  get 'signup' => 'users#new', as: 'signup'


  get 'search' => 'search#new', as: 'search'

  get '/auth/google_oauth2' => 'callbacks#new'
  get '/auth/google_oauth2/callback' => 'callbacks#index'

  get '/auth/facebook' => 'callbacks#new'
  get '/auth/facebook/callback' => 'callbacks#index'

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  after_create :create_notification

  belongs_to :user
  belongs_to :video
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  has_many :notifications

  validates :content, presence: true

  before_save :format_media, :check_times

  def editable_by?(user)
    user == self.user || user == self.video.user
  end

  def check_times
    if self.new_record?
      if self.start_time == "" || self.start_time.to_i < 0
        self.start_time = "0"
      elsif self.end_time == "" || self.end_time.to_i < 0
        self.end_time = "0"
      end
    end
  end

  def format_media
    if self.new_record?
      if self.media_type == "IMAGE"
        self.content = "<img src='#{self.content}' class='comment-image'></img>"
      elsif self.media_type == "VIDEO"
        youtube_id = self.content.split("=").last
        self.content = "<iframe src='//www.youtube.com/embed/#{youtube_id}'></iframe>"
      end
    end
  end

  def find_video_parent
    return self.commentable if self.commentable_type == "Video"
    self.commentable.find_video_parent
  end

  def self.format_times(seconds)
    seconds = seconds.to_i
    min = (seconds / 60).floor.to_s
    if seconds % 60 == 0
      sec = "00"
    elsif seconds % 60 < 10
      sec = "0" + (seconds % 60).to_s
    else
      sec = (seconds % 60).to_s
    end
    min + ":" + sec
  end

private

  def create_notification
    @parent = self.commentable
    @user = User.find_by(id: @parent.user_id)
      Notification.create(
       commentable_id: self.commentable.id,
       commentable_type: self.commentable_type,
       user_id: @user.id,
       comment_id: self.id,
       read: false
      )
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :authenticate_user!, except: [:show, :index]

  def new
    if params[:parent_id]
      @comment = Comment.find(params[:parent_id])
      @subcomment = @comment.comments.new
    else
      @video = Video.find(params[:video_id])
      @comment = @video.comments.new
    end
  end

  def index
    @video = Video.find(params[:video_id])
    @comments = @video.comments
  end

  def edit
    video = Video.find(params[:video_id])
    @comment = video.comments.find(params[:id])
  end

  def update
    video = Video.find(params[:video_id])
    @comment = video.comments.find(params[:id])
    if @comment.update_attributes(comment_params)
      redirect_to video_path(video)
    else
      render :edit
    end
  end

  def create
    if params[:comment_id]
      @parent_comment = Comment.find(params[:comment_id])
      @comment = @parent_comment.comments.build(comment_params)
    else
      video = Video.find(params[:video_id])
      @comment = video.comments.build(comment_params)
    end

    if @comment.save
      current_user.comments << @comment
      if request.xhr?
        new_comment = @comment.as_json({:include => { :user => { :methods => :gravatar_url, only: [:id, :user]}}})
        render json: new_comment
      else
        redirect_to video_path(@comment.find_video_parent)
      end
    else
      flash[:notice] = "Sorry, your comment didn't save"
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
    @commentable = @comment.commentable
  end

  def destroy
    comment = Comment.find(params[:id])
    notification = Notification.where(comment_id: comment.id)
    notification.delete_all
    comment.destroy if comment.editable_by?(current_user)
    render text: "ok"
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :start_time, :end_time, :media_url, :media_type).merge(user_id: current_user)
  end
end

app/views/comments/_comment.html.erb
<% if comment.user %>
  <h5>
    <%= link_to comment.user.name, user_path(comment.user) %>
    <% if comment.created_at %>
    - <%= comment.created_at.strftime("%B %d, %Y") %></h5>
    <% end %>
  </h5>
  <p>
    @<%= Comment.format_times(comment.start_time) %>-<%= Comment.format_times(comment.end_time)%><br>
    <br>
    <%= comment.content %>
  </p>

  <%= link_to "Respond to comment", new_comment_path(comment.id) %>
  <ul>
    <%= render comment.comments %>
  </ul>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@video, @comment] do |f| %>
  <%= f.label "Content" %>
  <%= f.text_area :content, placeholder: "Content" %>

  <%= f.label "Start Time" %>
  <%= f.text_field :start_time, placeholder: "e.g. 4:11" %>

  <%= f.label "End Time" %>
  <%= f.text_field :end_time, placeholder: "e.g. 4:25" %>

  <%= f.label "Media Type" %>
  <%= f.radio_button :media_type, 'TEXT', :value => 'text', :checked => true %>
  <%= label :media_type, 'TEXT' %>

  <%= f.radio_button :media_type, 'VIDEO', :value => 'video' %>
  <%= label :media_type, 'VIDEO' %>

  <%= f.radio_button :media_type, 'IMAGE', :value =>'image' %>
  <%= label :media_type, 'IMAGE' %>

  <div class="action">
    <ul class="button-group">
      <li>
        <button class="small button" name="commit" id="createNewComment" type="submit">Submit</button>
      </li>
    </ul>
  </div>
<% end %>

app/views/comments/_subform.html.erb
<%= form_for [@subcomment], url: video_comments_path(@comment.commentable, comment_id: @comment.id) do |f| %>

  <p><%= f.label "Content" %></p>
  <p><%= f.text_area :content, placeholder: "Content" %></p>

  <p><%= f.text_field :media_url, placeholder: "Link for media" %></p>
  <p><%= f.label "Media Type" %></p>

  <%= f.radio_button :media_type, 'TEXT', :value => 'text', :checked => true %>
  <%= label :media_type, 'TEXT' %>
  <%= f.radio_button :media_type, 'VIDEO', :value => 'video' %>
  <%= label :media_type, 'VIDEO' %>
  <%= f.radio_button :media_type, 'IMAGE', :value =>'image' %>
  <%= label :media_type, 'IMAGE' %>

  <p><%= f.submit "Enter" %></p>
<% end %>

app/views/comments/index.html.erb
<ul>
  <%= render @comments %>
</ul>

app/views/comments/new.html.erb
<% if @video %>
  <%= render 'form' %>
<% else %>
  <%= render 'subform' %>
<% end %>

app/views/comments/show.html.erb
<%= render @comment %>