config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :videos do
    resources :comments
  end
  resource :session, :only => [:new, :create, :destroy]
  resources :notifications
  resources :users, :except => [:destroy]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
  end
  resources :messages, only: [:new, :create]

  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  get 'signin' => 'sessions#new', as: 'signin'
  get 'signout' => 'sessions#destroy', as: 'signout'
  get 'signup' => 'users#new', as: 'signup'


  get 'search' => 'search#new', as: 'search'

  get '/auth/google_oauth2' => 'callbacks#new'
  get '/auth/google_oauth2/callback' => 'callbacks#index'

  get '/auth/facebook' => 'callbacks#new'
  get '/auth/facebook/callback' => 'callbacks#index'

  root 'welcome#index'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :get_mailbox
  before_action :get_conversation, except: [:index]
  before_action :get_box, only: [:index]

  def show
  end

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
    render partial: 'conversations/conversation', collection: @conversations if request.xhr?
  end

  def redirect_back_or(path)
    redirect_to request.referer || path
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end

    @box = params[:box]
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<li class="message_items">
  <%= link_to conversation.subject, conversation_path(conversation) %>

  <div>
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>
      <% if conversation.is_unread?(current_user) %>
        <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
      <% end %>
    <% end %>
  </div>

  <p>
    <%= render 'conversations/participants', conversation: conversation %>
  </p>

  <p><%= conversation.last_message.body %>
    <small>(<span><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small>
  </p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= image_tag participant.gravatar_url %> <%= participant.name %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<ul class="inline-list">
  <ul class="breadcrumbs">
    <%= mailbox_section 'inbox', @box, id: "inbox-link" %>
    <%= mailbox_section 'sent', @box, id: "sent-link" %>
    <%= mailbox_section 'trash', @box , id: "trash-link" %>
  </ul>

</ul>

<div class="row" style="height 10%">
  <div class="row">
    <div class="large-2 columns small-3"></div>
    <div class="large-10 columns">
      <h1 id="box-type" style="font-family: Century">Inbox</h1>
      <%= link_to 'Start a conversation', new_message_path, class: "button round success tiny", id: "message-button", :"data-reveal-id" => "sendmessage-modal" %>
    <ul id="messages">
      <%= render partial: 'conversations/conversation', collection: @conversations %>
    </ul>

      <%= will_paginate %>
    </div>
  </div>
</div>

<div id="render-messages" class="large-9 push-3 columns">

</div>

app/views/conversations/show.html.erb
<div class="message_box">
  <% page_header "Conversation" %><br>
  <h3><%= @conversation.subject %></h3>

  <div class="large-6 columns">
    <% @conversation.receipts_for(current_user).each do |receipt| %>
      <div class="row">
        <% message = receipt.message %>
        <div class="large-2 columns small-3"><img src="<%= message.sender.gravatar_url %>"/></div>
          <div class="large-10 columns">
            <p><strong><%= message.sender.name %> at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></strong> <%= message.body %></p>
          </div>
        </div>
    <% end %>

    <%= form_tag reply_conversation_path(@conversation), method: :post do %>
      <div class="form-group">
        <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
      </div>
      <div class="action">
          <ul class="button-group">
            <li>
              <button class="small button" name="commit" id="createNewMessage" type="submit">Send Message</button>
            </li>
          </ul>
        </div>
    <% end %>
  </div>
  <aside class="large-3 columns hide-for-small">
    <p>Chatting with:</p>
    <p><%= render 'conversations/participants', conversation: @conversation %><p>
  </aside>
</div>