config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :videos do
    resources :comments
  end
  resource :session, :only => [:new, :create, :destroy]
  resources :notifications
  resources :users, :except => [:destroy]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
  end
  resources :messages, only: [:new, :create]

  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  get 'signin' => 'sessions#new', as: 'signin'
  get 'signout' => 'sessions#destroy', as: 'signout'
  get 'signup' => 'users#new', as: 'signup'


  get 'search' => 'search#new', as: 'search'

  get '/auth/google_oauth2' => 'callbacks#new'
  get '/auth/google_oauth2/callback' => 'callbacks#index'

  get '/auth/facebook' => 'callbacks#new'
  get '/auth/facebook/callback' => 'callbacks#index'

  root 'welcome#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
    belongs_to :commentable
    belongs_to :comments
    belongs_to :users
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.notifications.order('created_at DESC')
    @unread_notifs = []
    @notifications.each do |notification|
      @unread_notifs << notification if notification.read == false
      notification.update_attribute(:read, true)
    end
  end

  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy
    redirect_to :back
  end
end

app/views/notifications/_notification.html.erb
<% if unread_notifs.include?(notification) %>
<li class="notification unread">
<% else %>
<li class="notification read">
<% end %>
  <%= link_to image_tag("trashbin.png", size: "25x20"), notification_path(notification.id), method: :delete %> <%= link_to " #{image_tag Comment.find_by(id: notification.comment_id).user.gravatar_url, size: "25x20"} #{Comment.find_by(id: notification.comment_id).user.name}".html_safe, user_path(Comment.find_by(id: notification.comment_id).user.id) %> commented on

  <% if notification.commentable_type = "Video" %>
    <%= link_to "your video", video_path(notification.commentable_id) %>: "<%= Comment.find_by(id: notification.comment_id).content %>"
  <% elsif notification.commentable_type = "Comment" %>

    <%= link_to "your comment", video_path(notification.commentable.commentable.id) %>: "<%= Comment.find_by(id: notification.comment_id).content %>"
  <% end %>
</li>

app/views/notifications/index.html.erb
<div class="row" style="height 10%">
  <div class="row">
    <div class="large-2 columns small-3"></div>
    <div class="large-10 columns">
      <h1 style="font-family: Century">Notifications</h1>
      <% if !@notifications.blank? %>
        <ul>
          <%= render  partial: "notifications/notification", collection: @notifications, locals: {unread_notifs: @unread_notifs} %>
        </ul>
      <% else %>
        <p>You have no notifications!</p>
      <% end %>
    </div>
  </div>
</div>