config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :videos do
    resources :comments
  end
  resource :session, :only => [:new, :create, :destroy]
  resources :notifications
  resources :users, :except => [:destroy]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
  end
  resources :messages, only: [:new, :create]

  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  get 'signin' => 'sessions#new', as: 'signin'
  get 'signout' => 'sessions#destroy', as: 'signout'
  get 'signup' => 'users#new', as: 'signup'


  get 'search' => 'search#new', as: 'search'

  get '/auth/google_oauth2' => 'callbacks#new'
  get '/auth/google_oauth2/callback' => 'callbacks#index'

  get '/auth/facebook' => 'callbacks#new'
  get '/auth/facebook/callback' => 'callbacks#index'

  root 'welcome#index'

end

app/views/layouts/_search.html.erb
<div class="row collapse">
  <div class="large-8 small-9 columns">
    <%= form_tag search_path, :id => 'search_form', method: 'get' do %>
      <%= text_field_tag :search, params[:search] %>
  </div>
  <div class="large-4 small-3 columns">
    <a href="#" name="search-button" id="search-button" class="success button expand">Search</a>
  </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>tubeGenius</title>

    <%= stylesheet_link_tag    "application" %>
    <link href='https://fonts.googleapis.com/css?family=Londrina+Outline' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Londrina+Solid' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <%= csrf_meta_tags %>
  </head>

<body>

  <div class="fixed">
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="<%= videos_path %>"><span id="t">tube</span><span id="g">Genius</span></a></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <% if current_user %>
            <li class="divider"></li>
            <% if unread_notifications > 0 %>
              <li class="notifications">
              <%= link_to image_tag("notification.png", size: "25x20"), notifications_path %>
              </li>
            <% end %>

            <li class="divider"></li>

            <% if unread_messages > 0 %>

              <li class="message-box">
                <%= link_to image_tag("full_message_box.png", size: "25x20"), conversations_path %>
              </li>
            <% else %>

              <li class="message-box">
                <%= link_to image_tag("empty_message_box.png", size: "25x20"), conversations_path %>
              </li>
            <% end %>

            <li class="has-form">
              <%= render '/layouts/search' %>
            </li>
            <li class="active">
              <a href="#" data-reveal-id="videocreate-modal" id="buttonForVideoCreate">Create a Video
              </a>
            </li>

            <li id="dropdown-menu">
              <a href="#" data-dropdown="hover1" data-options="is_hover:true; hover_timeout:1000">
                <%= image_tag(current_user.gravatar_url size: '25x20') %>
                 <%= current_user.name %>
               </a>
              <ul id="hover1" class="f-dropdown" data-dropdown-content>
                <li class="dropdown-item"><a href="<%= user_path(current_user) %>">View Profile</a></li>
                <li class="dropdown-item"><a href="<%= conversations_path %>">Conversations</a></li>
                <li class="divider"></li>
                <li class="dropdown-item"><a href="<%= signout_path %>">Sign Out</a></li>
              </ul>
            </li>

          <% else %>

            <li class="active">
              <a href="#" data-reveal-id="signup-modal" id="buttonForSignUp">Sign Up</a>
            </li>
            <li>
              <a href="#" data-reveal-id="signin-modal" id="buttonForSignIn">Sign In</a>
            </li>

          <% end %>
        </ul>
      </section>
    </nav>
  </div>

  <div id="signup-modal" class="reveal-modal tiny" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog"><%= render "users/signup" %></div>

  <div id="signin-modal" class="reveal-modal tiny" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog"><%= render "sessions/signin" %></div>

  <div id="user-modal" class="reveal-modal tiny" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog"></div>

  <div id="videocreate-modal" class="reveal-modal tiny" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog"><%= render "videos/new" %></div>

  <div id="sendmessage-modal" class="reveal-modal tiny" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog"></div>

  <%= yield %>

</body>

</html>